from pyvis.network import Network
from models.expense_manager import ExpenseManager

# The idea was mine to generate these kinds of graphs but used AI to generate the entire base code 
# Generated By AI (Gemini) after detailed instructions from me
# Small changes were done by me to tailor to my needs and then I gave more instructions to the AI to resolve bugs
# More than 95% of the work was done by AI but again needed to give instructions

def _clean_id(node_id):
    """
    Helper to normalize IDs to Integers.
    Handles inputs like "User_22", "22", or 22 -> returns 22.
    """
    if isinstance(node_id, int):
        return node_id
    if isinstance(node_id, str):
        # Strip "User_" prefix if present
        clean = node_id.replace("User_", "")
        try:
            return int(clean)
        except ValueError:
            # If it's some other string, return as is (fallback)
            return node_id
    return node_id

def generate_graph_html(manager: ExpenseManager, filepath: str):
    """
    Generates the PyVis graph and injects the Focus Mode JS.
    """
    # Initialize Network
    net = Network(height="850px", width="100%", bgcolor="white", font_color="black", directed=True)
    net.force_atlas_2based()
    
    # 1. Add Nodes
    # We use enumerate, so uid is guaranteed to be an Integer 0, 1, 2...
    for uid, bal in enumerate(manager.net_balances):
        clean_uid = _clean_id(uid)
        
        if abs(bal) > 0.01: 
            color = "#006c00" if bal > 0 else "#bb0000"
        else: 
            color = "#616161"
        
        title = f"User ID: {clean_uid}\nNet Balance: ${bal:.2f}"
        size = 10 + (abs(bal) / 10)
        
        net.add_node(clean_uid, label=f"User {clean_uid}", title=title, color=color, size=size)

    # 2. Add Edges
    limit = 3000
    for i, t in enumerate(manager.transactions):
        if i > limit: break
        
        # Robustly clean IDs to ensure they match the Nodes added above
        u = _clean_id(t.payer_id)
        v = _clean_id(t.payee_id)
        
        width = 1 + (t.amount / 50)
        
        try:
            net.add_edge(u, v, title=f"${t.amount:.2f}", width=width, color="#555555", arrows='to')
        except Exception as e:
            print(f"Skipping invalid edge {u}->{v}: {e}")
            continue

    # 3. Save and Inject JS
    net.write_html(filepath)
    _inject_focus_mode_js(filepath)

def _inject_focus_mode_js(filename):
    """
    Injects custom JavaScript for click-to-focus functionality.
    """
    js_logic = """
    network.on("selectNode", function (params) {
        if (params.nodes.length === 1) {
            var nodeId = params.nodes[0];
            var connectedNodes = network.getConnectedNodes(nodeId);
            var connectedEdges = network.getConnectedEdges(nodeId);
            
            connectedNodes.push(nodeId);

            var allNodes = nodes.get(); 
            var allEdges = edges.get();

            var nodesToUpdate = [];
            var edgesToUpdate = [];

            for (var i = 0; i < allNodes.length; i++) {
                var n = allNodes[i];
                if (connectedNodes.indexOf(n.id) === -1) {
                    if (!n.hidden) { n.hidden = true; nodesToUpdate.push(n); }
                } else {
                    if (n.hidden) { n.hidden = false; nodesToUpdate.push(n); }
                }
            }

            for (var i = 0; i < allEdges.length; i++) {
                var e = allEdges[i];
                if (connectedEdges.indexOf(e.id) === -1) {
                    if (!e.hidden) { e.hidden = true; edgesToUpdate.push(e); }
                } else {
                    if (e.hidden) { e.hidden = false; edgesToUpdate.push(e); }
                }
            }
            
            if (nodesToUpdate.length > 0) nodes.update(nodesToUpdate);
            if (edgesToUpdate.length > 0) edges.update(edgesToUpdate);
        }
    });

    network.on("deselectNode", function (params) {
        var allNodes = nodes.get();
        var allEdges = edges.get();
        
        var nodesToUpdate = [];
        var edgesToUpdate = [];
        
        for (var i = 0; i < allNodes.length; i++) {
            if (allNodes[i].hidden) {
                allNodes[i].hidden = false;
                nodesToUpdate.push(allNodes[i]);
            }
        }
        
        for (var i = 0; i < allEdges.length; i++) {
            if (allEdges[i].hidden) {
                allEdges[i].hidden = false;
                edgesToUpdate.push(allEdges[i]);
            }
        }
        
        if (nodesToUpdate.length > 0) nodes.update(nodesToUpdate);
        if (edgesToUpdate.length > 0) edges.update(edgesToUpdate);
    });
    """

    try:
        with open(filename, "r") as f:
            html_content = f.read()
            
        if "return network;" in html_content:
            new_content = html_content.replace("return network;", f"{js_logic}\nreturn network;")
            
            with open(filename, "w") as f:
                f.write(new_content)
    except Exception as e:
        print(f"Error injecting JS: {e}")